### ISSUE TITLE
Server with ID "*****" not found!

### ISSUE THREAD

**Issue by moutonnoireu** [Angush/trellobot#1]
Hello !

Tried using your bot but I'm stuck on this message : 

```
root@cd877668d43c:/opt/trellobot/trellobot# node trellobot.js
Server with ID "****" not found! I can't function without a valid server and channel.
Please add the correct server ID to your conf file, or if the conf data is correct, ensure I have proper access.
You may need to add me to your server using this link: [redacted]
```

(I removed the server ID and invite link from this issue).
I'm 100% sure to I have completed the configuration file correctly. I even used the generated invite link, but nope. Did I miss something ?

**Comment by Angush** [comment]
I just noticed the invite link it gives has my testing client ID hardcoded. Whoops!

Try this: `https://discordapp.com/api/oauth2/authorize?client_id=CLIENTIDHERE&permissions=0&scope=bot` (replacing `CLIENTIDHERE` with your own client ID, naturally).

**Comment by moutonnoireu** [comment]
Ah, shoots. It works well now ! Thanks :)
Do you accept feature request ?

**Comment by Angush** [comment]
I could give it a shot.
