### ISSUE TITLE
Bot cannot authorize Trello account

### ISSUE THREAD

**Issue by im-deepfriedwater** [Angush/trellobot#7]
Hello, when clicking the link the bot gives about authorizing the bot with a Trello account. The bot replies with this: 
```
Either you didn't select a board or you haven't authorized your Trello account with Discord! Please authorize here: https://trello.snazzah-is.cool/auth
```

I get the following error after attempting to go through the link:

![image](https://user-images.githubusercontent.com/16827894/51580340-f3667e00-1e78-11e9-9256-4315d6fb145c.png)

**Comment by Angush** [comment]
That's... not part of the bot. 🤔  Must be built-in to a dependency. Ignore that. The only thing you need to do to set it up is follow the instructions in the readme. There's no "authorizing your Trello account with Discord" or anything like that involved.

**Comment by im-deepfriedwater** [comment]
Ahh, got it, thanks! Sorry for using up your time with such a simple issue. Closing since it is working.
